### PR TITLE
add copy_to2

### PR DESCRIPTION
**Pull request by vituri**
I messed a bit with the project.toml to add CSV and MySQL; I also created the file copy_to.jl where I wrote a draft of how to make inserts in MariaDB from julia dataframes. I called my new function `copy_to2` to avoid clashes with the other one.

Its arguments are 
```
function copy_to2(df::DataFrames.AbstractDataFrame, table_name, con::MySQL.Connection; replace = false)
```
where we need a dataframe, a table_name (in the database), a connection (for now, just the MySQL/MariaDB), and the replace argument (which is false by default).

### CODE REVIEW

**Comment by drizk1** [comment]
Thank you so much, this looks great. Idk why the documenter is failing, this is something with a recent julia or documenter update because I am newly having this issue as well. 

As for the PR, a few small changes if you dont mind - 
Can you add these changes to the MySQLext - this will allow us to keep MySQL, DBInterface, and CSV as weakdeps to keep the package light. 

For `copy_to2`  , it can also be named `copy_to` and with multiple dispatch. as long as the con is  `con::MySQL.Connection` there should not be conflict issue. When you define it in the ext, you will just need to prefix it with `TidierDB.`


I have not tried running a docstring from an ext file. If it gives you issues, dont worry about it and i can try sorting it out/putting in a `replace` arg in the copy_to for main and just explaining there

thank you!

**Comment by vituri** [comment]
I added the code to the ext as recommended; I have no idea how to test it locally. I guess it is time to learn about extensions...

**Comment by drizk1** [comment]
Ok this is near perfect.. last thing (im sorry since I dont actually know how to take over a PR yet and easily edit it) 

can you change the argument order in `copy_to` to the following so the connection comes firs so that it matches the others? 
`function copy_to2(con::MySQL.Connection, df::DataFrames.AbstractDataFrame, table_name; replace = false)`

as for the deps, it looks like MySQL, CSV, DBInterface are still in `[deps]` rather than `[weakdeps]` ?  would u mind moving those to the weakdeps?

and then ill merge and release asap.. just finishing up one other refinement to allow multiple TidierDB queries to be joined in a single chain

**Comment by vituri** [comment]
No problem! See if it's ok now.

**Comment by drizk1** [comment]
Looks. Good last thing is like 54 `end` for the end of the module is now in the middle of the MySQL ext. So that `end` just needs to be moved to the last line.

**Comment by vituri** [comment]
Ops! The "end" got into the mess. Fixed.

**Comment by drizk1** [comment]
Hey @vituri random question,

Would MySQL.load work for `copy_to` ? Or was there a reason that CSV was the preferred method? Just curious

**Comment by vituri** [comment]
Hi, @drizk1 ! 

I guess the reason was that uploading a CSV was faster than using copy_to; unfortunately, I don't have access to my old MariaDB database anymore to test this...

**Comment by drizk1** [comment]
No worries! I had a feeling that was the case, but just wanted to make sure

**Pull request merged**
